### ISSUE TITLE
Unable to download org data on new chef 12.0.1 install

### ISSUE THREAD

**Issue by troyready** [opscode/knife-ec-backup#57]
I'm testing the backup process on a new Chef 12.0.1 server, and knife-ec-backup seems to only be downloading users & acls (leaving the organizations folder empty). No message about organizations is printed to the console.

My test environment is a clean install on Ubuntu 14.04, with one organization and associated user. I'm calling knife-ec-backup using `sudo /opt/opscode/embedded/bin/knife ec backup ./ --with-user-sql` on the server.

Any way I could help troubleshoot this further?

**Comment by stevendanna** [comment]
Hi @troyready.  What version are you seeing this on?  I believe this should be fixed in the most recent beta release.

**Comment by troyready** [comment]
Yeah, you're exactly right -- not sure how I missed that, sorry! I just tossed ruby2 & the pre-release gem onto the server and it appears to be working perfectly.

Thanks!
